### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.webjars.WebJarExtractor$Cache

### ISSUE THREAD

**Issue by tanin47** [sbt/sbt-js-engine#108]
I'm using the version 1.3.0-M4, and it seems that it depends on the webjars-locator-core's version that doesn't have WebJarExtractor$Cache anymore.

The stacktrace looks like:

```
java.lang.NoClassDefFoundError: org.webjars.WebJarExtractor$Cache
	at com.typesafe.sbt.jse.SbtJsEngine$.<init>(SbtJsEngine.scala:104)
	at com.typesafe.sbt.jse.SbtJsEngine$.<clinit>(SbtJsEngine.scala)
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:407)
	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:24)
	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:32)
	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:37)
```

I also notice that sbt-js-engine 1.2.3 isn't published anymore. Is that intentional?

Not blocking because I can clone sbt-js-engine 1.2.3 locally and use that.

Thank you so much.

**Comment by mkurz** [comment]
Hmm.. not sure how you ran into that. Do you use sbt-js-engine standalone or with a Play application? And yes I upgraded to a newer webjars-locator-core version that does not use the cache anymore.

> I also notice that sbt-js-engine 1.2.3 isn't published anymore. Is that intentional?

I think it still is published but not on maven central but another repo, not maven central: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/

**Comment by tanin47** [comment]
Thank you for the repo.

I've found that my SBT plugin doesn't need sbt-js-engine. It only needs sbt-web. I think we can close this.

**Comment by djx314** [comment]
@mkurz
Same issue, and remove
``` sbt
addSbtPlugin("com.vmunier"                       % "sbt-web-scalajs"          % "1.2.0")
```
is OK. It seems that need to wait the depts update in [vmunier/sbt-web-scalajs](https://github.com/vmunier/sbt-web-scalajs)

**Comment by mkurz** [comment]
@djx314 yes I guess sbt web plugins need to be updates now.
