### ISSUE TITLE
npm dependency resolution from local folder doesn't work

### ISSUE THREAD

**Issue by aindlq** [sbt/sbt-js-engine#34]
npm supports resolution of dependencies from local folder: https://docs.npmjs.com/files/package.json#local-paths . But it doesn't work with sbt-js-engine.
I'm using  JsEngineKeys.engineType := JsEngineKeys.EngineType.Node.

And in general there are some issues with dependencies resolution in sbt-js-engine. For example I've noticed that dependencies resolution using https://docs.npmjs.com/files/package.json#github-urls is buggy as well, sometimes it checkouts wrong branch/tag. but it works without any problems when I run "npm install" from command-line.

**Comment by aindlq** [comment]
ok, it seems the problem is that https://github.com/typesafehub/npm uses npm v.1.3.26. The latest version is 2.11.0. Any plans to update npm?

**Comment by benmccann** [comment]
@aindlq is this issue fixed for you now? typesafehub/npm has been using 2.11.2 for quite awhile (and we're about to release a much newer version)

**Comment by aindlq** [comment]
meanwhile I switched to native resolution with "yarn", more performant and much more predictable :)
