### ISSUE TITLE
It does not detect Node.JS on Debian by default

### ISSUE THREAD

**Issue by v6ak** [sbt/sbt-js-engine#39]
1. Install Node.JS Debian package.
2. Use sbt-js-engine

Expected results: Node.JS is found in the system.

Actual results: Node.JS is not found in the system.

Cause: Debian package contains just /usr/bin/nodejs binary, but sbt-js-engine needs /usr/bin/node.

Workaround: Install nodejs-legacy, which adds symlink /usr/bin/node -> nodejs.

**Comment by nadirabid** [comment]
Ran into the same issue on an AWS ubuntu vm.

**Comment by benmccann** [comment]
Thanks for reporting. This is an issue in typesafehub/npm. I've moved the report there to increase the chance that someone sees it and addresses it. https://github.com/typesafehub/npm/issues/15

**Comment by benmccann** [comment]
Thanks for reporting. This is an issue in typesafehub/js-engine. I've moved the report there to increase the chance that someone sees it and addresses it. https://github.com/typesafehub/js-engine/issues/56
