### ISSUE TITLE
Output in wrong directory?

### ISSUE THREAD

**Issue by aij** [sbt/sbt-js-engine#45]
Currently the output of npm gets put into a `node_modules` in the base directory.

Per [SBT Best Practices](http://www.scala-sbt.org/0.13/docs/Best-Practices.html), it should instead be under the `target` directory, although I'm not sure whether `sourceManaged`, `resourceManaged`, or somewhere else would be more appropriate.

Sorry to nitpick, but it's just weird to have all output files under `target` except for these.

**Comment by huntc** [comment]
That's an npm convention. We're justing bridging npm

**Comment by aij** [comment]
By that logic, sbt should intermix .class files alongside their .java and .scala files since that's the javac/scalac convention.
