### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt-js-engine#52]
@wsargent mind doing one last release so that we can make use of the latest js-engine and npm?

**Comment by wsargent** [comment]
Okay, assume 1.2.0 is new version

**Comment by benmccann** [comment]
Yeah, that makes sense

**Comment by wsargent** [comment]
I do not see this in https://bintray.com/sbt-web/sbt-plugin-releases/sbt-js-engine so I assume I did not actually release this...

**Comment by benmccann** [comment]
Agreed. I don't think 1.2.0 has been released yet

**Comment by wsargent** [comment]
```
java.lang.RuntimeException: error uploading to com.typesafe.sbt/sbt-js-engine/scala_2.10/sbt_0.13/1.2.0/docs/sbt-js-engine-javadoc.jar: {"message":"forbidden"}
	at bintray.BintrayIvyRepository.put(Resolver.scala:59)
	at org.apache.ivy.plugins.resolver.RepositoryResolver.put(RepositoryResolver.java:234)
	at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
	at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:381)
	at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:380)
```

That's why -- I don't have publish rights here.  Pinging the usual suspects.

**Comment by benmccann** [comment]
Any progress on getting publish rights?

**Comment by wsargent** [comment]
@benmccann Apparently YOU have publish rights. :-)

**Comment by benmccann** [comment]
Ah, thanks!! Good to know :-)

Released.

**Comment by wsargent** [comment]
Relevant link https://bintray.com/sbt-web has 4 members -- you are on there, I am not :-/

**Comment by benmccann** [comment]
I don't see a way to add you unfortunately. James's email is on there, so maybe you'll have to ask him
