### ISSUE TITLE
Update executeJs to accept handlers for stdout and stderr

### ISSUE THREAD

**Issue by ian-speers** [sbt/sbt-js-engine#62]
## Proposal
I would like to propose a minor update to the `executeJs` of `SbtJsTask` wherein stdout and stderr callbacks can be provided and forwarded to `executeJsOnEngine`. This could easily be accomplished by adding `stderr: Option[String => Unit] = None`, and `stdout: Option[String => Unit] = None` as optional arguments to the method. These callbacks could be forwarded to `executeJsOnEngine` if provided, or default to the appropriate `state.log`. This approach would maintain reverse compatibility.

## Context
I am trying to execute a script which sends it's output to stdout rather than writing to an output file. As far as I can tell, the current implementation of `executeJs` does not provide a mechanism for handling this output.

**Comment by mkurz** [comment]
Fixed by #95, will ship in version 1.3.0 (there is a 1.3.0-M1 release already).
